### ISSUE TITLE
Implementação do protótipo do figma em código

### ISSUE THREAD

**Issue by SamirBuarque** [pedro0402/Projeto-LES#8]

**Comment by SamirBuarque** [comment]
![image](https://github.com/user-attachments/assets/8d09d092-647f-49b2-8ec6-91269b189b10)

**Comment by SamirBuarque** [comment]
![image](https://github.com/user-attachments/assets/79b962d5-3202-4967-bd7e-ffeab759700e)

Protótipo criado!

**Comment by Lcsouzaa21** [comment]
Criei a tela de FileUpdate (Tela de Arquivo) e o Zeus criou a tela Tools (de Ferramentas).

**Comment by SamirBuarque** [comment]
Ajustei os códigos html e css para componentes React.

**Comment by SamirBuarque** [comment]
Faltam alguns ajustes no css na pagina de enviar os arquivos. Vou criar outra issue somente para isso, essa aqui estou fechando, pois o código ja foi criado.
